agent:
  name: bio_deployer
  model: gpt-4o
  tools:
    - github
    - railway
    - telegram

workflow:
  - name: create_github_repo
    action: GitHubAPI.create_repo
    args:
      name: bio-dashboard-bot
      private: true

  - name: generate_and_commit_files
    action: GitHubAPI.commit_files
    args:
      files:
        - requirements.txt
        - run_agent.py
        - playbook.yaml
        - .env

  - name: create_railway_project
    action: RailwayAPI.create_project
    args:
      name: bio-dashboard-bot

  - name: set_railway_env
    action: RailwayAPI.set_environment_variables
    args:
      TG_TOKEN: ${TG_TOKEN}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      RAILWAY_TOKEN: ${RAILWAY_TOKEN}
      USER_CHAT_ID: ${USER_CHAT_ID}

  - name: deploy_from_github
    action: RailwayAPI.deploy
    args: {}

  - name: poll_deploy_status
    action: RailwayAPI.wait_for_deploy
    args:
      timeout: 300

  - name: set_telegram_webhook
    action: TelegramAPI.set_webhook
    args:
      url: ${DEPLOY_URL}/webhook

  - name: notify_user
    action: TelegramAPI.send_message
    args:
      chat_id: ${USER_CHAT_ID}
      text: "✅ Бот деплоен и готов: t.me/your_bot_username"
